
import { Category, Scheme } from './types.ts';

export const COLORS = {
  primary: '#0B3C5D',
  accent: '#138808',
  softBG: '#E8F5E9',
  text: '#263238',
  white: '#FFFFFF'
};

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'bn', name: 'বাংলা (Bengali)' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'es', name: 'Español (Spanish)' },
  { code: 'fr', name: 'Français (French)' },
  { code: 'de', name: 'Deutsch (German)' }
];

export const CATEGORIES: Category[] = [
  { id: 'agri', icon: '🌾' },
  { id: 'edu', icon: '🎓' },
  { id: 'health', icon: '🏥' },
  { id: 'jobs', icon: '💼' },
  { id: 'startup', icon: '🚀' },
  { id: 'women', icon: '👩' },
  { id: 'housing', icon: '🏠' },
  { id: 'fin', icon: '💰' },
  { id: 'skill', icon: '🛠️' },
  { id: 'social', icon: '🤝' },
  { id: 'tech', icon: '💻' },
  { id: 'state', icon: '🏛️' },
  { id: 'upcoming', icon: '📅' },
];

export const POPULAR_SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    name: 'PM-KISAN Samman Nidhi',
    category: 'agri',
    description: '',
    benefits: ['₹6,000 annual transfer', '3 installments', 'Direct Bank Transfer'],
    eligibility: ['Small and marginal farmers'],
    status: 'Active Scheme'
  },
  {
    id: 'ayushman',
    name: 'Ayushman Bharat (PM-JAY)',
    category: 'health',
    description: '',
    benefits: ['₹5 Lakh health cover', 'Cashless service'],
    eligibility: ['Low-income families'],
    status: 'Active Scheme'
  },
  {
    id: 'pm-vishwakarma',
    name: 'PM Vishwakarma Yojana',
    category: 'artisan',
    description: '',
    benefits: ['ID Cards', 'Skill training', 'Low-interest loans'],
    eligibility: ['Artisans and craftspeople'],
    status: 'Active Scheme'
  }
];

export const UI_TEXT: Record<string, any> = {
  en: {
    nav_login: "Login / Sign Up",
    search_placeholder: "Search for schemes (e.g., 'Farmer')...",
    cat_title: "Browse by Category",
    cat_agri: "Agriculture & Farmers",
    cat_edu: "Education & Scholarships",
    cat_health: "Health & Insurance",
    cat_jobs: "Jobs & Employment",
    cat_startup: "Startup & Business",
    cat_women: "Women & Child Development",
    cat_housing: "Housing & Urban Development",
    cat_fin: "Financial Support & Banking",
    cat_skill: "Skill Development",
    cat_social: "Social Welfare",
    cat_tech: "Technology & Digital India",
    cat_state: "State Government Schemes",
    cat_upcoming: "Upcoming Government Schemes",
    hero_title: "SwayamHelp",
    hero_sub: "Your AI-powered partner for Government Schemes.",
    dashboard: "Dashboard",
    logout: "Logout",
    namaste: "Namaste 🙏",
    chatPrompt: "How can I assist you today?",
    disclaimer: "Disclaimer: This information is for general guidance only. Please verify details on official government portals before taking any action.",
    closingLine: "Would you like me to check your eligibility or guide you step-by-step through the application process?",
    profile: "User Profile",
    account: "Your Account",
    help: "Help & Support",
    uniqueId: "SwayamHelp ID",
    aboutUs: "About Us",
    findEligible: "Find Eligible Schemes",
    myApps: "My Applications",
    copy: "© 2026 SwayamHelp - Digital Seva Initiative",
    speechStart: "Listening...",
    search: "Search",
    signUp: "Sign Up",
    login: "Login",
    clear_filter: "Clear Filter",
    explore_btn: "Explore & Apply",
    login_view_btn: "Login to View",
    flow_title: "Digital Seva Simplified",
    flow_sub: "Accessing government benefits shouldn't be a challenge. We guide you through every step of the journey.",
    step1_title: "Discover",
    step1_desc: "Browse hundreds of Central and State schemes tailored for your needs.",
    step2_title: "Check",
    step2_desc: "Answer a few simple questions to know if you are eligible instantly.",
    step3_title: "Apply",
    step3_desc: "Get step-by-step guidance on documentation and portal navigation.",
    pm_kisan_desc: "Direct income support of ₹6,000 per year to farmer families.",
    nsp_desc: "Single portal for all scholarships provided by central and state govts.",
    ayushman_desc: "World's largest health insurance scheme for vulnerable families.",
    pm_vishwakarma_desc: "Holistic support for artisans and craftspeople across India.",
    lakhpati_didi_desc: "Empowering women in SHGs to earn at least ₹1 Lakh annually.",
    live_ngsp: "Live from National Portal",
    fetching_live: "Connecting to NGSP for 2026 updates...",
    roadmap_title: "Application Roadmap",
    roadmap_step1: "Eligibility Check",
    roadmap_step2: "Required Documents",
    roadmap_step3: "Final Action",
    go_official_btn: "Go to Official Website",
    reassurance_msg: "You are now being redirected to the official government portal. Use your SwayamHelp ID {{id}} to track your progress here later.",
    quick_eligibility: "Check Eligibility",
    quick_how_it_works: "How it Works",
    quick_resources: "Official Resources",
    resource_india: "India.gov.in",
    resource_myscheme: "myScheme.gov.in",
    resource_digital_india: "Digital India"
  },
  hi: {
    nav_login: "लॉगिन / साइन अप",
    search_placeholder: "योजनाओं की खोज करें (जैसे, 'किसान')...",
    cat_title: "श्रेणी के अनुसार खोजें",
    cat_agri: "कृषि",
    cat_edu: "शिक्षा",
    cat_fin: "वित्त और सब्सिडी",
    cat_health: "स्वास्थ्य और बीमा",
    cat_women: "महिला सशक्तिकरण",
    cat_jobs: "रोजगार",
    cat_skill: "कौशल विकास",
    cat_artisan: "कारीगर",
    hero_title: "स्वयंहेल्प",
    hero_sub: "सरकारी योजनाओं के लिए आपका एआई-संचालित साथी।",
    dashboard: "डैशबोर्ड",
    logout: "लॉगआउट",
    namaste: "नमस्ते 🙏",
    chatPrompt: "आज मैं आपकी कैसे सहायता कर सकता हूँ?",
    disclaimer: "डिस्क्लेमर: यह जानकारी केवल सामान्य मार्गदर्शन के लिए है। किसी भी कार्रवाई से पहले आधिकारिक सरकारी पोर्टल पर विवरण सत्यापित करें।",
    closingLine: "क्या आप चाहेंगे कि मैं आपकी पात्रता की जांच करूं या आवेदन प्रक्रिया में आपका मार्गदर्शन करूं?",
    profile: "प्रोफ़ाइल",
    account: "आपका खाता",
    help: "सहायता और समर्थन",
    uniqueId: "स्वयंहेल्प आईडी",
    aboutUs: "हमारे बारे में",
    findEligible: "पात्र योजनाएं",
    myApps: "मेरे आवेदन",
    savedSchemes: "पसंदीदा योजनाएं",
    copy: "© 2026 स्वयंहेल्प - डिजिटल सेवा पहल",
    speechStart: "सुन रहा हूँ...",
    search: "खोज",
    signUp: "साइन अप",
    login: "लॉगिन",
    clear_filter: "फिल्टर हटाएं",
    explore_btn: "देखें और आवेदन करें",
    login_view_btn: "देखने के लिए लॉगिन करें",
    flow_title: "डिजिटल सेवा अब आसान",
    flow_sub: "सरकारी लाभ प्राप्त करना अब चुनौतीपूर्ण नहीं होगा। हम यात्रा के हर कदम पर आपका मार्गदर्शन करते हैं।",
    step1_title: "खोजें",
    step1_desc: "अपनी आवश्यकताओं के लिए तैयार सैकड़ों केंद्रीय और राज्य योजनाओं को ब्राउज़ करें।",
    step2_title: "जांचें",
    step2_desc: "तुरंत यह जानने के लिए कुछ सरल प्रश्नों के उत्तर दें कि क्या आप पात्र हैं।",
    step3_title: "आवेदन करें",
    step3_desc: "दस्तावेज़ीकरण और पोर्टल नेविगेशन पर चरण-दर-चरण मार्गदर्शन प्राप्त करें।",
    pm_kisan_desc: "किसान परिवारों को प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता।",
    nsp_desc: "केंद्र और राज्य सरकारों द्वारा प्रदान की जाने वाली सभी छात्रवृत्तियों के लिए एकल पोर्टल।",
    ayushman_desc: "कमजोर परिवारों के लिए दुनिया की सबसे बड़ी स्वास्थ्य बीमा योजना।",
    pm_vishwakarma_desc: "पूरे भारत में कारीगरों और शिल्पकारों के लिए समग्र सहायता।",
    lakhpati_didi_desc: "स्वयं सहायता समूहों में महिलाओं को सालाना कम से कम ₹1 लाख कमाने के लिए सशक्त बनाना।",
    live_ngsp: "राष्ट्रीय पोर्टल से लाइव",
    fetching_live: "2026 अपडेट के लिए NGSP से जुड़ रहे हैं...",
    roadmap_title: "आवेदन मार्गदर्शिका",
    roadmap_step1: "पात्रता जांच",
    roadmap_step2: "आवश्यक दस्तावेज़",
    roadmap_step3: "अंतिम चरण",
    go_official_btn: "आधिकारिक वेबसाइट पर जाएं",
    reassurance_msg: "अब आपको आधिकारिक सरकारी पोर्टल पर पुनर्निर्देशित किया जा रहा है। बाद में अपनी प्रगति को ट्रैक करने के लिए अपनी स्वयंहेल्प आईडी {{id}} का उपयोग करें।",
    quick_eligibility: "पात्रता जांचें",
    quick_how_it_works: "यह कैसे काम करता है",
    quick_resources: "आधिकारिक संसाधन",
    resource_india: "India.gov.in",
    resource_myscheme: "myScheme.gov.in",
    resource_digital_india: "Digital India"
  },
  te: {
    nav_login: "లాగిన్ / సైన్ అప్",
    search_placeholder: "పథకాల కోసం వెతకండి (ఉదా. 'రైతు')...",
    cat_title: "వర్గం వారీగా వెతకండి",
    cat_agri: "వ్యవసాయం",
    cat_edu: "విద్య",
    cat_fin: "ఆర్థిక & రాయితీలు",
    cat_health: "ఆరోగ్యం & ఇన్సూరెన్స్",
    cat_women: "మహిళా సాధికారత",
    cat_jobs: "ఉద్యోగం",
    cat_skill: "నైపుణ్యాభివృద్ధి",
    cat_artisan: "కుస్తీ కళాకారులు",
    hero_title: "SwayamHelp",
    hero_sub: "ప్రభుత్వ పథకాల కోసం మీ AI-ఆధారిత భాగస్వామి.",
    dashboard: "డ్యాష్‌బోర్డ్",
    logout: "లాగౌట్",
    namaste: "నమస్తే 🙏",
    chatPrompt: "నేను మీకు ఈ రోజు ఎలా సహాయపడగలను?",
    disclaimer: "నిరాకరణ: ఈ సమాచారం సాధారణ మార్గదర్శకత్వం కోసం మాత్రమే. ఏదైనా చర్య తీసుకునే ముందు దయచేసి అధికారిక ప్రభుత్వ పోర్టల్‌లలో వివరాలను ధృవీకరించండి.",
    closingLine: "నేను మీ అర్హతను తనిఖీ చేయాలా లేదా దరఖాస్తు ప్రక్రియలో మీకు మార్గనిర్దేశం చేయాలా?",
    profile: "ప్రొఫైల్",
    account: "మీ ఖాతా",
    help: "సహాయం & మద్దతు",
    uniqueId: "SwayamHelp ID",
    aboutUs: "మా గురించి",
    findEligible: "అర్హత ఉన్న పథకాలు",
    myApps: "నా దరఖాస్తులు",
    savedSchemes: "సేవ్ చేసిన పథకాలు",
    copy: "© 2026 SwayamHelp - డిజిటల్ సేవా కార్యక్రమం",
    speechStart: "వింటున్నాను...",
    search: "శోధన",
    signUp: "సైన్ అప్",
    login: "లాగిన్",
    clear_filter: "ఫిల్టర్ తొలగించు",
    explore_btn: "చూడండి & దరఖాస్తు చేయండి",
    login_view_btn: "చూడటానికి లాగిన్ చేయండి",
    flow_title: "డిజిటల్ సేవ ఇప్పుడు సులభం",
    flow_sub: "ప్రభుత్వ ప్రయోజనాలను పొందడం ఒక సవాలుగా ఉండకూడదు. ప్రయాణంలో ప్రతి అడుగులో మేము మీకు మార్గనిర్దేశం చేస్తాము.",
    step1_title: "కనుగొనండి",
    step1_desc: "మీ అవసరాలకు అనుగుణంగా రూపొందించబడిన వందలాది కేంద్ర మరియు రాష్ట్ర పథకాలను బ్రౌజ్ చేయండి.",
    step2_title: "తనిఖీ చేయండి",
    step2_desc: "మీరు అర్హులో కాదో తక్షణమే తెలుసుకోవడానికి కొన్ని సాధారణ ప్రశ్నలకు సమాధానం ఇవ్వండి.",
    step3_title: "దరఖాస్తు చేయండి",
    step3_desc: "డాక్యుమెంటేషన్ మరియు పోర్టల్ నావిగేషన్ గురించి దశల వారీ మార్గదర్శకత్వం పొందండి.",
    pm_kisan_desc: "రైతు కుటుంబాలకు ఏడాదికి ₹6,000 ప్రత్యక్ష ఆదాయ మద్దతు.",
    nsp_desc: "కేంద్ర మరియు రాష్ట్ర ప్రభుత్వాలు అందించే అన్ని స్కాలర్‌షిప్‌ల కోసం ఒకే పోర్టల్.",
    ayushman_desc: "బలహీన వర్గాల కుటుంబాల కోసం ప్రపంచంలోనే అతిపెద్ద ఆరోగ్య బీమా పథకం.",
    pm_vishwakarma_desc: "భారతదేశవ్యాప్తంగా ఉన్న కళాకారులు మరియు చేతివృత్తుల వారికి సమగ్ర మద్దతు.",
    lakhpati_didi_desc: "SHGలలోని మహిళలు ఏటా కనీసం ₹1 లక్ష సంపాదించేలా సాధికారత కల్పించడం.",
    live_ngsp: "నేషనల్ పోర్టల్ నుండి లైవ్",
    fetching_live: "2026 అప్‌డేట్‌ల కోసం NGSPకి కనెక్ట్ అవుతోంది...",
    roadmap_title: "అప్లికేషన్ రోడ్‌మ్యాప్",
    roadmap_step1: "అర్హత తనిఖీ",
    roadmap_step2: "కావలసిన పత్రాలు",
    roadmap_step3: "చివరి దశ",
    go_official_btn: "అధికారిక వెబ్‌సైట్‌కు వెళ్లండి",
    reassurance_msg: "మీరు ఇప్పుడు అధికారిక ప్రభుత్వ పోర్టల్‌కి మళ్లించబడుతున్నారు. మీ పురోగతిని తర్వాత ట్రాక్ చేయడానికి మీ SwayamHelp ID {{id}}ని ఉపయోగించండి."
  },
  bn: {
    nav_login: "লগইন / সাইন আপ",
    search_placeholder: "স্কিম খুঁজুন (যেমন, 'কৃষক')...",
    cat_title: "বিভাগ অনুযায়ী খুঁজুন",
    cat_agri: "কৃষি",
    cat_edu: "শিক্ষা",
    cat_fin: "অর্থ ও ভর্তুকি",
    cat_health: "স্বাস্থ্য ও বীমা",
    cat_women: "নারী ক্ষমতায়ন",
    cat_jobs: "কর্মসংস্থান",
    cat_skill: "দক্ষতা বৃদ্ধি",
    cat_artisan: "কারিগর",
    hero_title: "SwayamHelp",
    hero_sub: "সরকারি প্রকল্পের জন্য আপনার AI-চালিত সহযোগী।",
    dashboard: "ড্যাশবোর্ড",
    logout: "লগআউট",
    namaste: "নমস্তে 🙏",
    chatPrompt: "আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
    disclaimer: "দাবিত্যাগ: এই তথ্য শুধুমাত্র সাধারণ নির্দেশনার জন্য। কোনো পদক্ষেপ নেওয়ার আগে অনুগ্রহ করে অফিসিয়াল সরকারি পোর্টালে বিস্তারিত যাচাই করুন।",
    closingLine: "আপনি কি চান আমি আপনার যোগ্যতা পরীক্ষা করি বা আবেদন প্রক্রিয়ার মাধ্যমে আপনাকে ধাপে ধাপে গাইড করি?",
    profile: "প্রোফাইল",
    uniqueId: "SwayamHelp ID",
    aboutUs: "আমাদের সম্পর্কে",
    findEligible: "যোগ্য স্কিম খুঁজুন",
    myApps: "আমার আবেদন",
    savedSchemes: "সংরক্ষিত স্কিম",
    copy: "© 2026 SwayamHelp - ডিজিটাল সেবা উদ্যোগ",
    speechStart: "শুনছি...",
    search: "অনুসন্ধান",
    signUp: "সাইন আপ",
    login: "লগইন",
    clear_filter: "ফিল্টার মুছুন",
    explore_btn: "দেখুন ও আবেদন করুন",
    login_view_btn: "দেখার জন্য লগইন করুন",
    flow_title: "ডিজিটাল সেবা এখন সহজ",
    flow_sub: "সরকারি সুবিধা পাওয়া চ্যালেঞ্জ হওয়া উচিত নয়। আমরা আপনাকে যাত্রার প্রতিটি ধাপে গাইড করি।",
    step1_title: "আবিষ্কার করুন",
    step1_desc: "আপনার প্রয়োজনের জন্য তৈরি শত শত কেন্দ্রীয় এবং রাজ্য স্কিম ব্রাউজ করুন।",
    step2_title: "পরীক্ষা করুন",
    step2_desc: "আপনি যোগ্য কিনা তা অবিলম্বে জানতে কয়েকটি সহজ প্রশ্নের উত্তর দিন।",
    step3_title: "আবেদন করুন",
    step3_desc: "ডকুমেন্টেশন এবং পোর্টাল নেভিগেশন সম্পর্কে ধাপে ধাপে নির্দেশনা পান।",
    pm_kisan_desc: "কৃষক পরিবারগুলির জন্য বছরে ৬,০০০ টাকার সরাসরি আয় সহায়তা।",
    nsp_desc: "কেন্দ্রীয় এবং রাজ্য সরকার কর্তৃক প্রদত্ত সমস্ত বৃত্তির জন্য একক পোর্টাল।",
    ayushman_desc: "অসহায় পরিবারগুলির জন্য বিশ্বের বৃহত্তম স্বাস্থ্য বীমা প্রকল্প।",
    pm_vishwakarma_desc: "সারা ভারত জুড়ে কারিগর এবং হস্তশিল্পীদের জন্য সামগ্রিক সহায়তা।",
    lakhpati_didi_desc: "SHG-এর মহিলাদের বার্ষিক অন্তত ১ লক্ষ টাকা উপার্জনে ক্ষমতায়ন করা।",
    live_ngsp: "ন্যাশনাল পোর্টাল থেকে লাইভ",
    fetching_live: "২০২৬ আপডেটের জন্য NGSP-এর সাথে সংযোগ করা হচ্ছে...",
    roadmap_title: "আবেদন রোডম্যাপ",
    roadmap_step1: "যোগ্যতা যাচাই",
    roadmap_step2: "প্রয়োজনীয় নথিপত্র",
    roadmap_step3: "চূড়ান্ত পদক্ষেপ",
    go_official_btn: "অফিসিয়াল ওয়েবসাইটে যান",
    reassurance_msg: "আপনাকে এখন অফিসিয়াল সরকারি পোর্টালে পাঠানো হচ্ছে। আপনার অগ্রগতি পরে ট্র্যাক করতে আপনার SwayamHelp ID {{id}} ব্যবহার করুন।"
  },
  mr: {
    nav_login: "लॉगिन / साइन अप",
    search_placeholder: "योजना शोधा (उदा. 'शेतकरी')...",
    cat_title: "वर्गानुसार शोधा",
    cat_agri: "कृषी",
    cat_edu: "शिक्षण",
    cat_fin: "वित्त आणि सबसिडी",
    cat_health: "आरोग्य आणि विमा",
    cat_women: "महिला सक्षमीकरण",
    cat_jobs: "रोजगार",
    cat_skill: "कौशल्य विकास",
    cat_artisan: "कारीगर",
    hero_title: "SwayamHelp",
    hero_sub: "सरकारी योजनांसाठी आपला AI-चालित भागीदार.",
    dashboard: "डॅशबोर्ड",
    logout: "लॉगआउट",
    namaste: "नमस्ते 🙏",
    chatPrompt: "मी आज आपली कशी मदत करू शकतो?",
    disclaimer: "डिस्क्लेमर: ही माहिती केवळ सामान्य मार्गदर्शनासाठी आहे. कोणतीही कारवाई करण्यापूर्वी कृपया अधिकृत सरकारी पोर्टलवर तपशील तपासा.",
    closingLine: "मी तुमची पात्रता तपासावी किंवा अर्ज प्रक्रियेत तुम्हाला टप्प्याटप्प्याने मदत करावी असे तुम्हाला वाटते का?",
    profile: "प्रोफाइल",
    uniqueId: "SwayamHelp ID",
    aboutUs: "आमच्याबद्दल",
    findEligible: "पात्र योजना शोधा",
    myApps: "माझे अर्ज",
    savedSchemes: "जतन केलेल्या योजना",
    copy: "© 2026 SwayamHelp - डिजिटल सेवा उपक्रम",
    speechStart: "ऐकत आहे...",
    search: "शोधा",
    signUp: "साइन अप",
    login: "लॉगिन",
    clear_filter: "फिल्टर काढा",
    explore_btn: "पहा आणि अर्ज करा",
    login_view_btn: "पाहण्यासाठी लॉगिन करा",
    flow_title: "डिजिटल सेवा आता सोपी",
    flow_sub: "सरकारी लाभ मिळवणे आता आव्हानात्मक नसेल. आम्ही तुम्हाला प्रवासाच्या प्रत्येक टप्प्यावर मदत करतो.",
    step1_title: "शोधा",
    step1_desc: "तुमच्या गरजांनुसार शेकडो केंद्रीय आणि राज्य योजना पहा.",
    step2_title: "तपासा",
    step2_desc: "तुम्ही पात्र आहात का हे त्वरित जाणून घेण्यासाठी काही सोप्या प्रश्नांची उत्तरे द्या.",
    step3_title: "अर्ज करा",
    step3_desc: "दस्तऐवज आणि पोर्टल नेव्हिगेशनवर टप्प्याटप्प्याने मार्गदर्शन मिळवा.",
    pm_kisan_desc: "शेतकरी कुटुंबांना वर्षाला ६,००० रुपयांचे थेट उत्पन्न साहाय्य.",
    nsp_desc: "केंद्र आणि राज्य सरकारांनी प्रदान केलेल्या सर्व शिष्यवृत्तींसाठी एकल पोर्टल.",
    ayushman_desc: "असुरक्षित कुटुंबांसाठी जगातील सर्वात मोठी आरोग्य विमा योजना.",
    pm_vishwakarma_desc: "संपूर्ण भारतातील कारागीर आणि शिल्पकारांना सर्वांगीण पाठबळ.",
    lakhpati_didi_desc: "SHG मधील महिलांना वर्षाकाठी किमान १ लाख रुपये कमवण्यासाठी सक्षम करणे.",
    live_ngsp: "राष्ट्रीय पोर्टलवरून थेट",
    fetching_live: "2026 अपडेट्ससाठी NGSP शी कनेक्ट करत आहे...",
    roadmap_title: "अर्ज मार्गदर्शिका",
    roadmap_step1: "पात्रता तपासणी",
    roadmap_step2: "आवश्यक कागदपत्रे",
    roadmap_step3: "अंतिम पाऊल",
    go_official_btn: "अधिकृत वेबसाइटवर जा",
    reassurance_msg: "तुम्हाला आता अधिकृत सरकारी पोर्टलवर नेले जात आहे. नंतर तुमची प्रगती पाहण्यासाठी तुमचा SwayamHelp ID {{id}} वापरा."
  },
  ta: {
    nav_login: "உள்நுழை / பதிவு செய்",
    search_placeholder: "திட்டங்களைத் தேடுங்கள் (எ.கா, 'விவசாயி')...",
    cat_title: "வகைகளின்படி தேடுங்கள்",
    cat_agri: "விவசாயம்",
    cat_edu: "கல்வி",
    cat_fin: "நிதி மற்றும் மானியங்கள்",
    cat_health: "சுகாதாரம் மற்றும் காப்பீடு",
    cat_women: "பெண் அதிகாரம்",
    cat_jobs: "வேலைவாய்ப்பு",
    cat_skill: "திறன் மேம்பாடு",
    cat_artisan: "கைவினைஞர்கள்",
    hero_title: "SwayamHelp",
    hero_sub: "அரசு திட்டங்களுக்கான உங்கள் AI-இயங்கும் துணை.",
    dashboard: "டாஷ்போர்டு",
    logout: "வெளியேறு",
    namaste: "நமஸ்தே 🙏",
    chatPrompt: "இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    disclaimer: "பொறுப்புத் துறப்பு: இந்தத் தகவல் பொதுவான வழிகாட்டுதலுக்கு மட்டுமே. ஏదేனும் நடவடிக்கை எடுப்பதற்கு முன் அதிகாரப்பூர்வ அரசு இணையதளங்களில் விவரங்களைச் சரிபார்க்கவும்.",
    closingLine: "உங்கள் தகுதியை நான் சரிபார்க்க வேண்டுமா அல்லது விண்ணப்பிக்கும் செயல்முறையில் உங்களுக்கு வழிகாட்ட வேண்டுமா?",
    profile: "சுயவிவரம்",
    uniqueId: "SwayamHelp ID",
    aboutUs: "எங்களைப் பற்றி",
    findEligible: "தகுதியான திட்டங்களைக் கண்டறியவும்",
    myApps: "என் விண்ணப்பங்கள்",
    savedSchemes: "சேமிக்கப்பட்ட திட்டங்கள்",
    copy: "© 2026 SwayamHelp - டிஜிட்டல் சேவா முயற்சி",
    speechStart: "கேட்டுக்கொண்டிருக்கிறது...",
    search: "தேடு",
    signUp: "பதிவு செய்க",
    login: "உள்நுழை",
    clear_filter: "வடிப்பானை அகற்று",
    explore_btn: "ஆராயுங்கள் & விண்ணப்பிக்கவும்",
    login_view_btn: "பார்க்க உள்நுழையவும்",
    flow_title: "டிஜிட்டல் சேவை இனி எளிது",
    flow_sub: "அரசு சலுகைகளைப் பெறுவது சவாலாக இருக்கக்கூடாது. பயணத்தின் ஒவ்வொரு அடியிலும் நாங்கள் உங்களுக்கு வழிகாட்டுவோம்.",
    step1_title: "கண்டறியுங்கள்",
    step1_desc: "உங்கள் தேவைகளுக்கேற்ப நூற்றுக்கணக்கான மத்திய மற்றும் மாநில திட்டங்களை உலாவுங்கள்.",
    step2_title: "சரிபார்க்கவும்",
    step2_desc: "நீங்கள் தகுதியுள்ளவரா என்பதை உடனடியாக அறிய சில எளிய கேள்விகளுக்கு பதிலளிக்கவும்.",
    step3_title: "விண்ணப்பிக்கவும்",
    step3_desc: "ஆவணங்கள் மற்றும் போர்டல் வழிசெலுத்தல் குறித்த படிப்படியான வழிகாட்டுதலைப் பெறுங்கள்.",
    pm_kisan_desc: "விவசாயக் குடும்பங்களுக்கு ஆண்டுக்கு ₹6,000 நேரடி வருமான ஆதரவு.",
    nsp_desc: "மத்திய மற்றும் மாநில அரசுகள் வழங்கும் அனைத்து கல்வி உதவித்தொகைகளுக்கான ஒற்றை போர்டல்.",
    ayushman_desc: "பாதிக்கப்படக்கூடிய குடும்பங்களுக்கான உலகின் மிகப்பெரிய மருத்துவ காப்பீட்டுத் திட்டம்.",
    pm_vishwakarma_desc: "இந்தியா முழுவதும் உள்ள கைவினைஞர்கள் మరియు தொழிலாளர்களுக்கு முழுமையான ஆதரவு.",
    lakhpati_didi_desc: "சுய உதவிக்குழுக்களில் உள்ள பெண்கள் ஆண்டுக்கு குறைந்தபட்சம் ₹1 லட்சம் வருமானம் ஈட்ட அதிகாரம் அளித்தல்.",
    live_ngsp: "தேசிய போர்ட்டலில் இருந்து நேரடி",
    fetching_live: "2026 புதுப்பிப்புகளுக்காக NGSP உடன் இணைகிறது...",
    roadmap_title: "விண்ணப்ப வழிமுறை",
    roadmap_step1: "தகுதி சரிபார்ப்பு",
    roadmap_step2: "தேவையான ஆவணங்கள்",
    roadmap_step3: "இறுதி நடவடிக்கை",
    go_official_btn: "அதிகாரப்பூர்வ இணையதளத்திற்குச் செல்லவும்",
    reassurance_msg: "நீங்கள் இப்போது அதிகாரப்பூர்வ அரசு இணையதளத்திற்கு மாற்றப்படுகிறீர்கள். உங்கள் முன்னேற்றத்தை பிறகு கண்காணிக்க உங்கள் SwayamHelp ID {{id}}-ஐப் பயன்படுத்தவும்."
  }
};

export const getTranslation = (lang: string) => UI_TEXT[lang] || UI_TEXT['en'];
